#//DEFINICIÓN DE LA ZONA HORARIA DEL PAIS DE DONDE ES EL SISTEMA PARA QUE LAS FECHAS Y HORAS EN EL SISTEMA SEAN LAS CORRECTAS:
spring.jackson.time-zone=America/Bogota

#PARÁMETROS DE CONEXIÓN A LA BASE DE DATOS:

#Definimos un puerto de ejecución para que no entre en conflicto con otras aplicaciones que esten usando el mismo:

#CUANDO SEA EN AMBIENTE DE DESARROLLO Y LA BASE DE DATOS SEA LOCAL:

#Puerto de conexión:
#server.port=8084
#Driver de conexión de oracle:
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#Conector de conexión, nombre del servidor, puerto de oracle y nombre de la base de datos:
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#Nombre de usuario de la base de datos:
#spring.datasource.username=TORRES_CEDE10
#Password de la base de datos:
#spring.datasource.password=oracle

#Definimos un puerto de ejecución para que no entre en conflicto con otras aplicaciones que esten usando el mismo:

#CUANDO EL PROYECTO ESTA DESPLEGADO EN AMBIENTE DE DESARROLLO Y LA BASE DE DATOS ESTE EN SERVIDOR DE APLICACIONES:

#Puerto de conexión:
server.port=8084
#Driver de conexión de oracle:
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#Conector de conexión, nombre del servidor, puerto de oracle y nombre de la base de datos:
spring.datasource.url=jdbc:oracle:thin:@172.22.3.116:11213:EJCGETDE
#Nombre de usuario de la base de datos:
spring.datasource.username=TORRES_CEDE10
#Password de la base de datos:
spring.datasource.password=oracle

#CUANDO EL PROYECTO ESTA DESPLEGADO EN AMBIENTE DE PRUEBAS O PRODUCCIÓN Y LA BASE DE DATOS ESTE EN SERVIDOR DE APLCIACIONES:

#Configuración para usar DATASOURCE JNDI (WebLogic):
#spring.datasource.jndi-name=jdbc/SADEC

#Evita inicialización automática de scripts SQL:
spring.sql.init.mode=never

#Pruebas de log para verificar la salida de registros:
spring.datasource.log-slow-queries=true
spring.jpa.show-sql=true

#Consultas durante la renderización:
spring.jpa.open-in-view=true

#DEFINICIÓN EXPLÍCITA DEL CONTEXT PATH (AGREGADA):
#server.servlet.context-path=/psiadmecejcnacv20

#Ajuste de memoria del backend:
spring.main.jvmargs=-Xms512m -Xmx6144m